### ISSUE TITLE
shutil has no attribute 'which'

### ISSUE THREAD

**Issue by pjkohler** [poldracklab/pydeface#28]
I get the error below when I try to run pydeface. It looks like it is grabbing shutil from my python 2.7 environment, which does not have the "which". It does so even if I run pydeface from my python 3.7 environment. Thanks. 

> Traceback (most recent call last):
> 
>   File "/Users/kohler/anaconda2/bin/pydeface", line 11, in <module>
>     load_entry_point('pydeface==2.0', 'console_scripts', 'pydeface')()
>   File "/Users/kohler/code/git/pydeface/pydeface/__main__.py", line 116, in main
>     pdu.deface_image(**vars(args))
>   File "/Users/kohler/code/git/pydeface/pydeface/utils.py", line 83, in deface_image
>     if shutil.which('fsl') is None:
> AttributeError: 'module' object has no attribute 'which'

**Comment by pjkohler** [comment]
Never mind, I installed while in the 2.7 environment, which gave rise to the error. Thanks.
