### ISSUE TITLE
 Strange error message

### ISSUE THREAD

**Issue by squinto13** [poldracklab/pydeface#29]
I'm receiving a strange error message when trying to install pydeface:
```
running install
running bdist_egg
running egg_info
writing pydeface.egg-info/PKG-INFO
writing dependency_links to pydeface.egg-info/dependency_links.txt
writing entry points to pydeface.egg-info/entry_points.txt
writing requirements to pydeface.egg-info/requires.txt
writing top-level names to pydeface.egg-info/top_level.txt
reading manifest file 'pydeface.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'pydeface.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.6-intel/egg
running install_lib
running build_py
creating build/bdist.macosx-10.6-intel/egg
creating build/bdist.macosx-10.6-intel/egg/pydeface
copying build/lib/pydeface/__init__.py -> build/bdist.macosx-10.6-intel/egg/pydeface
copying build/lib/pydeface/utils.py -> build/bdist.macosx-10.6-intel/egg/pydeface
creating build/bdist.macosx-10.6-intel/egg/pydeface/data
copying build/lib/pydeface/data/mean_reg2mean.nii.gz -> build/bdist.macosx-10.6-intel/egg/pydeface/data
copying build/lib/pydeface/data/facemask.nii.gz -> build/bdist.macosx-10.6-intel/egg/pydeface/data
copying build/lib/pydeface/__main__.py -> build/bdist.macosx-10.6-intel/egg/pydeface
byte-compiling build/bdist.macosx-10.6-intel/egg/pydeface/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.macosx-10.6-intel/egg/pydeface/utils.py to utils.cpython-36.pyc
byte-compiling build/bdist.macosx-10.6-intel/egg/pydeface/__main__.py to __main__.cpython-36.pyc
creating build/bdist.macosx-10.6-intel/egg/EGG-INFO
copying pydeface.egg-info/PKG-INFO -> build/bdist.macosx-10.6-intel/egg/EGG-INFO
copying pydeface.egg-info/SOURCES.txt -> build/bdist.macosx-10.6-intel/egg/EGG-INFO
copying pydeface.egg-info/dependency_links.txt -> build/bdist.macosx-10.6-intel/egg/EGG-INFO
copying pydeface.egg-info/entry_points.txt -> build/bdist.macosx-10.6-intel/egg/EGG-INFO
copying pydeface.egg-info/requires.txt -> build/bdist.macosx-10.6-intel/egg/EGG-INFO
copying pydeface.egg-info/top_level.txt -> build/bdist.macosx-10.6-intel/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/pydeface-2.0-py3.6.egg' and adding 'build/bdist.macosx-10.6-intel/egg' to it
removing 'build/bdist.macosx-10.6-intel/egg' (and everything under it)
Processing pydeface-2.0-py3.6.egg
Removing /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pydeface-2.0-py3.6.egg
Copying pydeface-2.0-py3.6.egg to /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
pydeface 2.0 is already the active version in easy-install.pth
Installing pydeface script to /Library/Frameworks/Python.framework/Versions/3.6/bin

Installed /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pydeface-2.0-py3.6.egg
Processing dependencies for pydeface==2.0
Searching for numpy
Reading https://pypi.python.org/simple/numpy/
Downloading https://files.pythonhosted.org/packages/d3/4b/f9f4b96c0b1ba43d28a5bdc4b64f0b9d3fbcf31313a51bc766942866a7c7/numpy-1.16.4.zip#sha256=7242be12a58fec245ee9734e625964b97cf7e3f2f7d016603f9e56660ce479c7
Best match: numpy 1.16.4
Processing numpy-1.16.4.zip
Writing /var/folders/lz/fhyd7st94td_q0cwz3vl6svr0000gn/T/easy_install-ol_r_qq4/numpy-1.16.4/setup.cfg
Running numpy-1.16.4/setup.py -q bdist_egg --dist-dir /var/folders/lz/fhyd7st94td_q0cwz3vl6svr0000gn/T/easy_install-ol_r_qq4/numpy-1.16.4/egg-dist-tmp-x4uhsz25
Running from numpy source directory.
/var/folders/lz/fhyd7st94td_q0cwz3vl6svr0000gn/T/easy_install-ol_r_qq4/numpy-1.16.4/setup.py:390: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
  run_build = parse_setuppy_commands()
non-existing path in 'numpy/distutils': 'site.cfg'
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'define_macros'
  warnings.warn(msg)
Could not locate executable gfortran
Could not locate executable f95
Could not locate executable f90
Could not locate executable f77
Could not locate executable xlf90
Could not locate executable xlf
Could not locate executable ifort
Could not locate executable ifc
Could not locate executable g77
Could not locate executable g95
Could not locate executable pgfortran
don't know how to compile Fortran code on platform 'posix'
ld: warning: ignoring file /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd, file was built for unsupported file format ( 0x2D 0x2D 0x2D 0x20 0x21 0x74 0x61 0x70 0x69 0x2D 0x74 0x62 0x64 0x2D 0x76 0x33 ) which is not the architecture being linked (x86_64): /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd
ld: dynamic main executables must link with libSystem.dylib for architecture x86_64
clang-4.0: error: linker command failed with exit code 1 (use -v to see invocation)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/sandbox.py", line 157, in save_modules
    yield saved
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/sandbox.py", line 248, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/sandbox.py", line 278, in run
    return func()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/sandbox.py", line 246, in runner
    _execfile(setup_script, ns)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/sandbox.py", line 47, in _execfile
    exec(code, globals, locals)
  File "/var/folders/lz/fhyd7st94td_q0cwz3vl6svr0000gn/T/easy_install-ol_r_qq4/numpy-1.16.4/setup.py", line 415, in <module>
  File "/var/folders/lz/fhyd7st94td_q0cwz3vl6svr0000gn/T/easy_install-ol_r_qq4/numpy-1.16.4/setup.py", line 407, in setup_package
  File "/var/folders/lz/fhyd7st94td_q0cwz3vl6svr0000gn/T/easy_install-ol_r_qq4/numpy-1.16.4/numpy/distutils/core.py", line 171, in setup
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 152, in run
    self.run_command("egg_info")
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/var/folders/lz/fhyd7st94td_q0cwz3vl6svr0000gn/T/easy_install-ol_r_qq4/numpy-1.16.4/numpy/distutils/command/egg_info.py", line 26, in run
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/var/folders/lz/fhyd7st94td_q0cwz3vl6svr0000gn/T/easy_install-ol_r_qq4/numpy-1.16.4/numpy/distutils/command/build_src.py", line 148, in run
  File "/var/folders/lz/fhyd7st94td_q0cwz3vl6svr0000gn/T/easy_install-ol_r_qq4/numpy-1.16.4/numpy/distutils/command/build_src.py", line 159, in build_sources
  File "/var/folders/lz/fhyd7st94td_q0cwz3vl6svr0000gn/T/easy_install-ol_r_qq4/numpy-1.16.4/numpy/distutils/command/build_src.py", line 292, in build_library_sources
  File "/var/folders/lz/fhyd7st94td_q0cwz3vl6svr0000gn/T/easy_install-ol_r_qq4/numpy-1.16.4/numpy/distutils/command/build_src.py", line 375, in generate_sources
  File "numpy/core/setup.py", line 667, in get_mathlib_info
RuntimeError: Broken toolchain: cannot link a simple C program

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 47, in <module>
    'pydeface = pydeface.__main__:main'
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 410, in run
    self.easy_install(spec, not self.no_deps)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 646, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 697, in install_item
    self.process_distribution(spec, dist, deps)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 742, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 850, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1122, in best_match
    return self.obtain(req, installer)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1134, in obtain
    return installer(requirement)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 665, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 695, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 876, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1115, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1101, in run_setup
    run_setup(setup_script, args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/sandbox.py", line 251, in run_setup
    raise
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 100, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 100, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/sandbox.py", line 169, in save_modules
    saved_exc.resume()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/sandbox.py", line 144, in resume
    six.reraise(type, exc, self._tb)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/_vendor/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/sandbox.py", line 157, in save_modules
    yield saved
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/sandbox.py", line 248, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/sandbox.py", line 278, in run
    return func()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/sandbox.py", line 246, in runner
    _execfile(setup_script, ns)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/sandbox.py", line 47, in _execfile
    exec(code, globals, locals)
  File "/var/folders/lz/fhyd7st94td_q0cwz3vl6svr0000gn/T/easy_install-ol_r_qq4/numpy-1.16.4/setup.py", line 415, in <module>
  File "/var/folders/lz/fhyd7st94td_q0cwz3vl6svr0000gn/T/easy_install-ol_r_qq4/numpy-1.16.4/setup.py", line 407, in setup_package
  File "/var/folders/lz/fhyd7st94td_q0cwz3vl6svr0000gn/T/easy_install-ol_r_qq4/numpy-1.16.4/numpy/distutils/core.py", line 171, in setup
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 152, in run
    self.run_command("egg_info")
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/var/folders/lz/fhyd7st94td_q0cwz3vl6svr0000gn/T/easy_install-ol_r_qq4/numpy-1.16.4/numpy/distutils/command/egg_info.py", line 26, in run
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/var/folders/lz/fhyd7st94td_q0cwz3vl6svr0000gn/T/easy_install-ol_r_qq4/numpy-1.16.4/numpy/distutils/command/build_src.py", line 148, in run
  File "/var/folders/lz/fhyd7st94td_q0cwz3vl6svr0000gn/T/easy_install-ol_r_qq4/numpy-1.16.4/numpy/distutils/command/build_src.py", line 159, in build_sources
  File "/var/folders/lz/fhyd7st94td_q0cwz3vl6svr0000gn/T/easy_install-ol_r_qq4/numpy-1.16.4/numpy/distutils/command/build_src.py", line 292, in build_library_sources
  File "/var/folders/lz/fhyd7st94td_q0cwz3vl6svr0000gn/T/easy_install-ol_r_qq4/numpy-1.16.4/numpy/distutils/command/build_src.py", line 375, in generate_sources
  File "numpy/core/setup.py", line 667, in get_mathlib_info
RuntimeError: Broken toolchain: cannot link a simple C program
---
This is the full conda list in my environment, showing numpy is there:

# Name                    Version                   Build  Channel
appnope                   0.1.0            py36hf537a9a_0  
attrs                     19.1.0                   py36_1  
backcall                  0.1.0                    py36_0  
blas                      1.0                         mkl  
bleach                    3.1.0                    py36_0  
brainiak                  0.8                      pypi_0    pypi
bz2file                   0.98                     py36_1  
ca-certificates           2019.6.16            hecc5488_0    conda-forge
cctools                   895                           1  
certifi                   2019.3.9                 py36_0    conda-forge
clang                     4.0.1                         1  
clang_osx-64              4.0.1               h1ce6c1d_16  
clangxx                   4.0.1                         1  
clangxx_osx-64            4.0.1               h22b1bf0_16  
click                     7.0                        py_0    conda-forge
compiler-rt               4.0.1                hcfea43d_1  
cycler                    0.10.0           py36hfc81398_0  
cython                    0.29.8           py36h0a44026_0  
dbus                      1.13.6               h90a0687_0  
decorator                 4.4.0                    py36_1  
defusedxml                0.6.0                      py_0  
entrypoints               0.3                      py36_0  
expat                     2.2.6                h0a44026_0  
freetype                  2.9.1                hb4e5f40_0  
funcsigs                  1.0.2                      py_3    conda-forge
future                    0.17.1                py36_1000    conda-forge
gettext                   0.19.8.1             h15daf44_3  
glib                      2.56.2               hd9629dc_0  
h5py                      2.9.0            py36h3134771_0  
hdf5                      1.10.4               hfa1e0ec_0  
html5lib                  1.0.1                      py_0    conda-forge
icu                       58.2                 h4b95b61_1  
intel-openmp              2019.4                      233  
ipykernel                 5.1.0            py36h39e3cac_0  
ipython                   7.5.0            py36h39e3cac_0  
ipython_genutils          0.2.0            py36h241746c_0  
ipywidgets                7.4.2                    py36_0  
isodate                   0.6.0                      py_1    conda-forge
jedi                      0.13.3                   py36_0  
jinja2                    2.10.1                   py36_0  
joblib                    0.13.2                   py36_0  
jpeg                      9b                   he5867d9_2  
jsonschema                3.0.1                    py36_0  
jupyter                   1.0.0                    py36_7  
jupyter_client            5.2.4                    py36_0  
jupyter_console           6.0.0                    py36_0  
jupyter_core              4.4.0                    py36_0  
keepalive                 0.5                        py_1    conda-forge
kiwisolver                1.1.0            py36h0a44026_0  
ld64                      274.2                         1  
libcxx                    4.0.1                hcfea43d_1  
libcxxabi                 4.0.1                hcfea43d_1  
libedit                   3.1.20181209         hb402a30_0  
libffi                    3.2.1                h475c297_4  
libgfortran               3.0.1                h93005f0_2  
libiconv                  1.15                 hdd342a3_7  
libpng                    1.6.37               ha441bb4_0  
libsodium                 1.0.16               h3efe00b_0  
libxml2                   2.9.9                hd80cff7_0    conda-forge
libxslt                   1.1.32            h33a18ac_1002    conda-forge
llvm                      4.0.1                         1  
llvm-lto-tapi             4.0.1                         1  
llvm-meta                 7.0.0                         0    conda-forge
llvm-openmp               4.0.1                hcfea43d_1  
lxml                      4.3.4            py36h08abf6f_0    conda-forge
markupsafe                1.1.1            py36h1de35cc_0  
matplotlib                3.1.0            py36h54f8f79_0  
mistune                   0.8.4            py36h1de35cc_0  
mkl                       2019.4                      233  
mkl-service               2.0.2            py36h1de35cc_0  
mkl_fft                   1.0.12           py36h5e564d8_0  
mkl_random                1.0.2            py36h27c97d8_0  
mpi                       1.0                     openmpi  
mpi4py                    2.0.0                    py36_0  
nbconvert                 5.5.0                      py_0  
nbformat                  4.4.0            py36h827af21_0  
ncurses                   6.1                  h0a44026_1  
networkx                  2.3                        py_0  
neurdflib                 5.0.0.post1                py_0    conda-forge
nibabel                   2.4.1                      py_0    conda-forge
nipype                    1.2.0                    py36_0    conda-forge
nitime                    0.7             py36h917ab60_1002    conda-forge
notebook                  5.7.8                    py36_0  
numpy                     1.15.4                   pypi_0    pypi
numpy-base                1.16.4           py36h6575580_0  
openmp                    7.0.0                h2d50403_0    conda-forge
openmpi                   3.1.3                hfa1e0ec_1  
openssl                   1.1.1b               h01d97ff_2    conda-forge
packaging                 19.0                       py_0    conda-forge
pandas                    0.24.2           py36h0a44026_0  
pandoc                    2.2.3.2                       0  
pandocfilters             1.4.2                    py36_1  
parso                     0.4.0                      py_0  
patsy                     0.5.1                    py36_0  
pcre                      8.43                 h0a44026_0  
pexpect                   4.7.0                    py36_0  
pickleshare               0.7.5                    py36_0  
pip                       19.1.1                   py36_0  
prometheus_client         0.6.0                    py36_0  
prompt_toolkit            2.0.9                    py36_0  
prov                      1.5.3                      py_0    conda-forge
psutil                    5.6.2            py36h1de35cc_0  
ptyprocess                0.6.0                    py36_0  
pybind11                  2.2.4            py36h04f5b5a_0  
pydicom                   1.2.2                      py_0    conda-forge
pydotplus                 2.0.2                      py_1    conda-forge
pygments                  2.4.0                      py_0  
pymanopt                  0.2.3                    pypi_0    pypi
pyparsing                 2.4.0                      py_0  
pyqt                      5.9.2            py36h655552a_2  
pyrsistent                0.14.11          py36h1de35cc_0  
python                    3.6.8                haf84260_0  
python-dateutil           2.8.0                    py36_0  
pytz                      2019.1                     py_0  
pyzmq                     18.0.0           py36h0a44026_0  
qt                        5.9.7                h468cd18_1  
qtconsole                 4.5.1                      py_0  
rdflib                    4.2.2                 py36_1000    conda-forge
readline                  7.0                  h1de35cc_5  
scikit-learn              0.21.2           py36h27c97d8_0  
scipy                     1.2.1            py36h1410ff5_0  
send2trash                1.5.0                    py36_0  
setuptools                41.0.1                   py36_0  
simplejson                3.16.1           py36h470a237_0    conda-forge
sip                       4.19.8           py36h0a44026_0  
six                       1.12.0                   py36_0  
sparqlwrapper             1.8.2                 py36_1000    conda-forge
sqlite                    3.28.0               ha441bb4_0  
statsmodels               0.9.0            py36h1d22016_0  
terminado                 0.8.2                    py36_0  
testpath                  0.4.2                    py36_0  
theano                    1.0.3            py36h04f5b5a_0  
tk                        8.6.8                ha441bb4_0  
tornado                   6.0.2            py36h1de35cc_0  
traitlets                 4.3.2            py36h65bd3ce_0  
traits                    5.1.1            py36h01d97ff_0    conda-forge
typing                    3.6.4                    py36_0  
wcwidth                   0.1.7            py36h8c6ec74_0  
webencodings              0.5.1                    py36_1  
wheel                     0.33.4                   py36_0  
widgetsnbextension        3.4.2                    py36_0  
xvfbwrapper               0.2.9                 py36_1000    conda-forge
xz                        5.2.4                h1de35cc_4  
zeromq                    4.3.1                h0a44026_3  
zlib                      1.2.11               h1de35cc_3  
```
Any idea what I'm doing wrong?

**Comment by muschellij2** [comment]
Probably look into something like the answers here: https://github.com/ContinuumIO/anaconda-issues/issues/9096

**Comment by ofgulban** [comment]
@squinto13 Did you figure out your problem?

**Comment by squinto13** [comment]
Yes, thank you!
